---
- 
  name: Find dpkg architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: arch

-
  name: Import GPG key
  become: yes
  ansible.builtin.get_url:
    url: "{{ item.key_url }}"
    dest: "/tmp/{{ item.key_name }}" 
    mode: '0644'
    force: yes

-
  name: Dearmor and copy the GPG key
  become: yes
  ansible.builtin.shell: gpg -o /usr/share/keyrings/{{ item.key_name }} --dearmor /tmp/{{ item.key_name }}

-    
  name: Add the repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch={{ arch.stdout }} signed-by=/usr/share/keyrings/{{ item.key_name }}] {{ item.repo_url }} {{ item.release }}
    state: present
    filename: "{{ item.repo_name }}"
