---
-
  name: Import/Dearmor/Copy the GPG key and add the repo
  import_role: 
    name: sokratisvas.apt_key_repo_installer 
  vars:
    - key_url: https://baltocdn.com/helm/signing.asc 
    - key_name: helm-gpg-key
    - repo_url: https://baltocdn.com/helm/stable/debian all main
    - repo_name: helm-repo

- 
  name: Update all Packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

-
  name: Install Helm
  become: yes
  ansible.builtin.apt:
    name: helm

