---
- 
  hosts: localhost
  
  vars:
    - dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
    - key_url:  'https://apt.releases.hashicorp.com/gpg'
    - key_dest: /tmp/packer-gpg-key
    - dearmored_key_dest: /usr/share/keyrings/packer.gpg  
    - repo_url: https://apt.releases.hashicorp.com
    - release: bullseye main 

  tasks:
    -
      name: Import Packer GPG key
      become: yes
      ansible.builtin.get_url:
        url: "{{ key_url }}"
        dest: "{{ key_dest }}" 
        mode: '0644'
        force: yes

    -
      name: Convert key in binary
      #ansible.builtin.command: gpg --dearmor < /tmp/packer-gpg-key > /usr/share/keyrings/packer-archive-keyring.gpg
      ansible.builtin.shell: sudo gpg --dearmor {{ key_dest }} | sudo tee {{ dearmored_key_dest }} 
      #ansible.builtin.command: sudo gpg --dearmor /tmp/packer-gpg-key | sudo tee /usr/share/keyrings/packer-archive-keyring.gpg 
       
    -
      name: Add the Packer repository
      become: yes
      ansible.builtin.apt_repository:
        repo: deb [arch={{ dpkg_arch }} signed-by={{ dearmored_key_dest }}] {{ repo_url }} {{ release }}
        state: present

    - 
      name: Update all Packages
      become: yes
      ansible.builtin.apt:
          update_cache: yes
          cache_valid_time: 86400

    - 
      name: Install Packer
      become: yes
      ansible.builtin.apt:
        name: packer 

