---
- 
  hosts: localhost

  vars:
    package_list:
      - key_url: https://apt.releases.hashicorp.com/gpg
        key_name: packer-gpg-key      
        repo_url: https://apt.releases.hashicorp.com
        repo_name: packer-repo
        release: bullseye main 
        package_installations:
          - packer

  tasks:
    - 
      name: Install all packages
      include_tasks: template.yml
      loop: "{{ package_list }}"
