---
- 
  hosts: localhost
  
  vars:
    - key_url:  https://apt.releases.hashicorp.com/gpg
    - key_name: packer-gpg-key      
    - repo_url: https://apt.releases.hashicorp.com
    - repo_name: packer-repo
    - release: bullseye main 

  tasks:
    -
      name: Find dpkg architecture
      ansible.builtin.shell: dpkg --print-architecture
      register: arch

    - debug:
        var: arch.stdout_lines

    -
      name: Get the dpkg Architecture
      set_fact:
        #dpkg_arch: "{{ arch.stdout }}"
        dpkg_arch: arch.stdout

    -
      name: Import Packer GPG key
      become: yes
      ansible.builtin.get_url:
        url: "{{ key_url }}"
        dest: "/tmp/{{ key_name }}" 
        mode: '0644'
        force: yes

    -
      name: Dearmor the GPG key
      become: yes
      ansible.builtin.shell: gpg --dearmor /tmp/{{ key_name }}
       
    -
      name: Copy the dearmored GPG key to /usr/share/keyrings/
      become: yes
      ansible.builtin.shell: tee /tmp/{{ key_name }} < /usr/share/keyrings/{{ key_name }} > /dev/null  

    -
      name: Add the Packer repository
      become: yes
      ansible.builtin.apt_repository:
        repo: deb [arch={{ dpkg_arch }} signed-by=/usr/share/keyrings/{{ key_name }}] {{ repo_url }} {{ release }}
        state: present
        filename: "{{ repo_name }}"

    - 
      name: Update all Packages
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400

    - 
      name: Install Packer
      become: yes
      ansible.builtin.apt:
        name: packer 
