---
- 
  name: Find dpkg architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: arch

-
  name: Get the dpkg Architecture
  set_fact:
    dpkg_arch: arch.stdout

-
  name: Import Packer GPG key
  become: yes
  ansible.builtin.get_url:
    url: "{{ item.key_url }}"
    dest: "/tmp/{{ item.key_name }}" 
    mode: '0644'
    force: yes

-
  name: Dearmor the GPG key
  become: yes
  ansible.builtin.shell: gpg --dearmor /tmp/{{ item.key_name }}
 
-    
  name: Copy the dearmored GPG key to /usr/share/keyrings/
  become: yes
  ansible.builtin.shell: tee /tmp/{{ item.key_name }} < /usr/share/keyrings/{{ item.key_name }} > /dev/null  

-    
  name: Add the Packer repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch={{ dpkg_arch }} signed-by=/usr/share/keyrings/{{ item.key_name }}] {{ item.repo_url }} {{ item.release }}
    state: present
    filename: "{{ item.repo_name }}"

-    
  name: Update all Packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

-    
  name: Install Packer
  become: yes
  ansible.builtin.apt:
    name: packer 

