---
-
  name: Import/Dearmor/Copy the GPG key and add the repo
  import_role: 
    name: sokratisvas.apt_key_repo_installer 
  vars:
    - key_url:  https://apt.releases.hashicorp.com/gpg
    - key_name: packer-gpg-key      
    - repo_url: https://apt.releases.hashicorp.com bullseye main
    - repo_name: packer-repo

- 
  name: Update all Packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

- 
  name: Install Packer
  become: yes
  ansible.builtin.apt:
    name: packer 
