---
-
  name: Include variables in vars/main.yml
  include_vars: 
    dir: vars
    files_matching: main.yml

-
  name: Import/Dearmor/Copy the GPG key and add the repo
  include_role: 
    name: roles/apt-key-repo-installer

- 
  name: Update all Packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

- 
  name: Install CRI-O
  become: yes
  ansible.builtin.apt:
    name: 
      - cri-o
      - cri-o-runc

