---
- 
  name: Install cri-o dependencies
  apt:
    name:
      - curl
      - gnupg2
      - libseccomp2
      - ca-certificates
      - apt-transport-https
      - software-properties-common
    state: present

  name: Import/Dearmor/Copy the kubic GPG key and add the repo
  import_role: 
    name: roles/apt-key-repo-installer
  vars:
    - key_url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_Testing/Release.key 
    - key_name: kubic-gpg-key
    - repo_url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_Testing/ /'
    - repo_name: kubic-repo

-
  name: Import/Dearmor/Copy the cri-o GPG key and add the repo
  import_role: 
    name: roles/apt-key-repo-installer
  vars:
    - key_url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.21:/1.21.7/Debian_Testing/Release.key
    - key_name: crio-gpg-key
    - repo_url: 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.21:/1.21.7/Debian_Testing /'
    - repo_name: crio-repo

- 
  name: Update all Packages
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

- 
  name: Install CRI-O
  become: yes
  ansible.builtin.apt:
    name: 
      - cri-o
      - cri-o-runc

