---
-
  name: Include variables in vars/main.yml
  include_vars: 
    dir: vars
    files_matching: main.yml

-
  name: Import/Dearmor/Copy the GPG key and add the repo
  include_role: 
    name: roles/apt-key-repo-installer
