---
-
  name: Install dependencies
  become: yes
  ansible.builtin.apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2 
      - software-properties-common

-
  name: Include variables in vars/main.yml
  include_vars: 
    dir: vars
    files_matching: main.yml

-
  name: Import/Dearmor/Copy the GPG key and add the repo
  include_role: 
    name: roles/apt-key-repo-installer

-
  name: Install Docker
  become: yes
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
