---
- 
  hosts: localhost

  vars:
    package_list:
      - key_url: https://apt.releases.hashicorp.com/gpg
        key_name: packer-gpg-key      
        repo_url: https://apt.releases.hashicorp.com
        repo_name: packer-repo
        release: bullseye main 
        package_dependencies: []
        package_installations:
          - packer

      - key_url: https://download.docker.com/linux/debian/gpg 
        key_name: docker-gpg-key
        repo_url: https://download.docker.com/linux/debian
        repo_name: docker-repo
        release: bullseye stable
        package_dependencies:
          - 'apt-transport-https'
          - 'ca-certificates'
          - 'curl'
          - 'gnupg2' 
          - 'software-properties-common'
        package_installations:
          - 'docker-ce'
          - 'docker-ce-cli'
          - 'containerd.io'

      - key_url: https://baltocdn.com/helm/signing.asc 
        key_name: helm-gpg-key
        repo_url: https://baltocdn.com/helm/stable/debian
        repo_name: helm-repo
        release: all main
        package_dependencies: []
        package_installations:
          - helm

  tasks:
    - 
      name: Install all packages
      include_tasks: template.yml
      loop: "{{ package_list }}"
